// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


var state = {
  contents: {
    movies: /* :: */[
      {
        title: "Wayne's World"
      },
      /* [] */0
    ]
  }
};

console.log(state.contents);

state.contents = {
  movies: /* :: */[
    {
      title: "Sharkboy and Lavagirl "
    },
    /* [] */0
  ]
};

console.log(state.contents);

exports.state = state;
/*  Not a pure module */
