// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Caml_obj = require("bs-platform/lib/js/caml_obj.js");

function printState(state, label) {
  console.log(label);
  console.log(state.contents);
  return /* () */0;
}

function viewTopMovies(state) {
  return {
          movies: /* array */[
            {
              title: "Wayne's World"
            },
            {
              title: "Wayne's World 2"
            },
            {
              title: "Unabomber"
            },
            {
              title: "Cat in the Hat"
            },
            {
              title: "Sharkboy and Lavagirl"
            }
          ],
          favoritedMovies: state.favoritedMovies
        };
}

function toggleFavoriteMovie(movie, state) {
  var match = List.filter((function (m) {
            return Caml_obj.caml_equal(m, movie);
          }))(state.favoritedMovies);
  var favoritedMovies = match ? List.filter((function (m) {
              return Caml_obj.caml_notequal(m, movie);
            }))(state.favoritedMovies) : /* :: */[
      movie,
      state.favoritedMovies
    ];
  return {
          movies: state.movies,
          favoritedMovies: favoritedMovies
        };
}

var Command = {
  viewTopMovies: viewTopMovies,
  toggleFavoriteMovie: toggleFavoriteMovie
};

exports.printState = printState;
exports.Command = Command;
/* No side effect */
