// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var TestLib = require("./TestLib.bs.js");
var Caml_array = require("bs-platform/lib/js/caml_array.js");
var MovieStarReason = require("./MovieStarReason.bs.js");

function testViewingMovies(param) {
  var state_movies = /* array */[];
  var state = {
    movies: state_movies,
    favoritedMovies: /* [] */0
  };
  var state$1 = MovieStarReason.Command.viewTopMovies(state);
  return TestLib.expect("Wayne's World", Caml_array.caml_array_get(state$1.movies, 0).title);
}

function testFavoritingMovies(param) {
  var title = "Movie 1";
  var state_movies = /* array */[{
      title: title
    }];
  var state = {
    movies: state_movies,
    favoritedMovies: /* [] */0
  };
  var state$1 = MovieStarReason.Command.toggleFavoriteMovie(Caml_array.caml_array_get(state_movies, 0), state);
  return TestLib.expect(List.hd(state$1.favoritedMovies).title, title);
}

var tests_000 = {
  test: testViewingMovies,
  description: "Viewing Movies"
};

var tests_001 = /* :: */[
  {
    test: testFavoritingMovies,
    description: "Favoriting Movies"
  },
  /* [] */0
];

var tests = /* :: */[
  tests_000,
  tests_001
];

TestLib.runTests(tests);

exports.testViewingMovies = testViewingMovies;
exports.testFavoritingMovies = testFavoritingMovies;
exports.tests = tests;
/*  Not a pure module */
